#include <iostream>
#include <string.h> 
using namespace std;

const double PI = 3.1415;

class Rectangle{
    private:
        double lenght {1};
        double width {1};
        string color = "white";

    public:
        Rectangle() = default; // default constructor generated by compiler
        Rectangle(double l,double w){
            this->lenght = l;
            this->width  = w;
        }
        double area(void){return lenght*width; }
        void set_color(void){
            cout << "select new rectangle color: "<<endl;
            cin >> this->color;
        }
        void get_color(void){
            cout<< "Rectangle color: "<<this->color<<endl;
        }
};

class Circle{
    private:
        double radius {};
        string color = "white";
    public: 
        Circle ( double r={0.5}){this->radius=r;};
        double area(void){return 2*PI*radius;}
        
};

int main(){
    Rectangle r1;
    Rectangle r2(2,2);
    cout <<"Area of r1 : "<<r1.area()<<endl;
    cout <<"Area of r2 : "<<r2.area()<<endl;
    r2.set_color();
    r2.get_color();
    return 0;
}

