#include <iostream>
using namespace std;

const double PI = 3.1415;

class Rectangle{
    private:
        double lenght {1};
        double width {1};
        
    public:
        Rectangle() = default; // default constructor generated by compiler
    double area(void){
        return lenght*width;

    }
};

class Circle{
    private:
        double radius {};

    public: 
        Circle ( double r={0.5}){this->radius=r;};
    double area(void){
        return 2*PI*radius;
    }
};

int main(){
    Rectangle r1;
    cout <<"Area of r1 : "<<r1.area()<<endl;

    Circle c1(2);
    cout <<"Area of c1 : "<<c1.area()<<endl;


    return 0;
}

