#ifndef TRIGONOMETRY_H
#define TRIGONOMETRY_H

#include <iostream>
#include <string.h>

#include "constants.h"

using namespace std;

class Rectangle{
    private:
        double lenght {1};
        double width {1};
        string color = "white";

    public:
        Rectangle() = default; // default constructor generated by compiler
        Rectangle(double l,double w);

        double area(void);
        void set_color(void);
        void get_color(void);
};

class Circle{
    private:
        double radius {};
        string color = "white";

    public: 
        Circle ( double r);

        double area(void);
        
};

#endif